version: '3.8'

services:
  app:
    build: .
    image: todo-app  # ← Nom fixe pour toujours écraser la même image
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql  # ← Même volume à chaque fois
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  mysql-data:  # ← Volume déclaré explicitement
