version: '3.8'

services:
  app:
    build: .
    image: todo-app-prod
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo_network

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    restart: unless-stopped
    networks:
      - todo_network

volumes:
  mysql_data:
    external: true

networks:
  todo_network:
    external: true

