version: '3.8'

services:
  app:
    build: .
    image: todo-app-prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql  # Volume persistant
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  mysql-data:  # Volume déclaré explicitement
