#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - openjdk-17-jre
  - apache2
  - curl
  - gnupg

runcmd:
  # Démarrer et activer docker
  - sudo apt update -y
  - sudo apt install docker.io -y
  - systemctl enable docker
  - systemctl start docker

  # Ajouter la clé Jenkins et repo
  - sudo apt update
  - sudo apt install fontconfig openjdk-21-jre -y
  - sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian/jenkins.io-2023.key
  - echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  - sudo apt-get update -y
  - sudo apt-get install jenkins -y

  # Ajouter Jenkins au groupe docker et démarrer Jenkins
  - usermod -aG docker jenkins
  - systemctl enable jenkins
  - systemctl start jenkins
  - systemctl restart jenkins

  # Attendre que Jenkins démarre et récupérer le mot de passe admin
  - bash -c "until curl -s http://localhost:8080 > /dev/null; do sleep 10; done"
  - PASSWORD=$(cat /var/lib/jenkins/secrets/initialAdminPassword)
  
  # Modifier la page par défaut d’Apache pour afficher le mot de passe Jenkins
  - sudo apt install apache2 -y
  - echo "Love from paul" > /var/www/html/index.html
  - echo "Jenkins initial admin password</h1><p>${PASSWORD}" > /var/www/html/index.html

  # Redémarrer Apache
  - systemctl restart apache2
